### ISSUE TITLE
percent in string value in resw file

### ISSUE THREAD

**Issue by SergeevGregory** [Julien-Mialon/StormCrossLocalization#2]
When I use your nuget package in my xamarin.android project I catch issue with percent in resw string. There is error: "Multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?". I can fix it manually by adding formatted="false" attribute to xml string... but it will be excellent if it will be done automatically.

**Comment by Julien-Mialon** [comment]
Hello,

I didn't encountered this issue yet so didn't know % should be escaped in android string resources. I will publish a new version of nuget package which fix this issue (adding formatted="false" to all string resources)

Thank you for your help on finding this issue.

**Comment by Julien-Mialon** [comment]
Ok, version 0.0.13 should fix the issue and it's now live on https://www.nuget.org/packages/Storm.CrossLocalization/

I didn't manage to reproduce your issue, could you give me an example string you had issue with ?

**Comment by SergeevGregory** [comment]
I tried 0.0.13 version, now it works fine! Big thanks :)
If you still need file, I may upload it anywhere.

**Comment by Julien-Mialon** [comment]
Just to be able to add some test on that case, If it's possible to have the file it could be good yes. Thank you.

**Comment by Julien-Mialon** [comment]
Fixed in version 0.0.13
