### ISSUE TITLE
Protection d'un backslash

### ISSUE THREAD

**Issue by VJubert** [Julien-Mialon/StormCrossLocalization#4]
Je dois avoir un backslash dans ma resource.
Le problème c'est qu'il faut que je le protège pour Android, mais pas pour iOS

(Pour un chaine de formattage)

**Comment by Julien-Mialon** [comment]
Sample string causing issue : {0:HH\hmm\mn} string with date formatting in resx.
Works on iOS (because \ is replaced by \\\\) but not Android where \ is not transformed.

Have to check if \ must be protected in Android for simple strings before doing some change

**Comment by VJubert** [comment]
A simple way to avoid the problem while the bug is not resolved : {0:HH}h{0:mm}mn

**Comment by Julien-Mialon** [comment]
After looking this up, it seems that backslash should be escaped for android, so this will be fixed in next release
